name: flutter_work_utils
description: Flutter Work utils for a faster work, the best utilities set
  together in a simple package
version: 0.1.1
homepage: https://github.com/Djcharles26/
repository: https://github.com/Djcharles26/flutter_work_utils.git

environment:
  sdk: ">=2.17.0 < 3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.0
  crypto: ^3.0.2
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter: null
