name: flutter_work_utils
description: Flutter Work utils for a faster work, the best utilities set together in a simple package
version: 0.0.2
homepage: https://github.com/Djcharles26/
repository: https://github.com/Djcharles26/flutter_work_utils.git

environment:
  sdk: ">=2.17.0 < 3.0.0"
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.2
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter: null
